### create
POST http://localhost:3000/create
Content-Type: application/json

{
  "name" : "Karl",
  "ware" : "Käse,Rot Wein",
  "ort" : "Paris",
  "datum": "2021-12-11",
  "status": 1
}

### create
POST http://localhost:3000/create
Content-Type: application/json

{
  "name" : "Annie",
  "ware" : "Rind,Weiße Wein",
  "ort" : "Lollar",
  "datum": "2021-12-11",
  "status": 1
}


### getListInfos
GET http://localhost:3000/read

### findbyId
POST http://localhost:3000/read
POST http://localhost:3000/update
Content-Type: application/json

{
  "id" : 14
}

### ändern
POST http://localhost:3000/update
Content-Type: application/json

{
  "id" : 2,
  "name" : "wolfgang",
  "ware" : "Käse,Rot Wein",
  "ort" : "München",
  "datum": "2021-12-11"

}

### delete
POST http://localhost:3000/delete
Content-Type: application/json

{
  "id" : 2
}

### sichern
GET http://localhost:3000/sichern








